name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Project
      run: g++ GithubActionTest/actiontest.cpp -std=c++17 -o test
    - name: Run Object File
      run: ./test 
